### ISSUE TITLE
vMotion hangs on vSphere 6 / vSPC on armhf

### ISSUE THREAD

**Issue by iamsi** [iamsi/vSPC.py#1]
trackback:
```
Traceback (most recent call last):
  File "build/bdist.linux-armv7l/egg/vSPC/server.py", line 112, in _queue_run
    queue.get()()
  File "build/bdist.linux-armv7l/egg/vSPC/server.py", line 224, in <lambda>
    self.task_queue.put(lambda: self.new_vm_data(vt))
  File "build/bdist.linux-armv7l/egg/vSPC/server.py", line 179, in new_vm_data
    neg_done = vt.negotiation_done()
  File "build/bdist.linux-armv7l/egg/vSPC/telnet.py", line 276, in negotiation_done
    self.process_available()
  File "build/bdist.linux-armv7l/egg/vSPC/telnet.py", line 273, in process_available
    self.process_rawq()
  File "build/bdist.linux-armv7l/egg/vSPC/telnet.py", line 156, in process_rawq
    self.option_callback(self.sock, c, NOOPT)
  File "build/bdist.linux-armv7l/egg/vSPC/telnet.py", line 415, in _option_callback
    getattr(self, meth)(data)
  File "build/bdist.linux-armv7l/egg/vSPC/telnet.py", line 346, in _handle_vmotion_begin
    cookie = data + struct.pack("i", hash(self) & 0xFFFFFFFF)
error: integer out of range for 'i' format code
```

**Comment by iamsi** [comment]
resolved
